<a href="https://colab.research.google.com/github/edisonc57/exercises/blob/main/Pandas%20practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np


* Array de NumPy:

Homogeneidad de datos: Los arrays de NumPy son homogéneos, lo que significa que todos los elementos dentro de un array deben ser del mismo tipo de datos. Esto asegura que las operaciones en los arrays sean eficientes y rápidas.

Funcionalidades matriciales: NumPy proporciona un conjunto de funciones y operaciones matriciales eficientes para trabajar con arrays multidimensionales. Es particularmente útil para operaciones numéricas y científicas.

Flexibilidad en dimensiones: Los arrays de NumPy pueden tener cualquier número de dimensiones, lo que permite trabajar con datos de varias formas.

* Serie de Pandas:

Homogeneidad y etiquetas: A diferencia de los arrays de NumPy, las Series de Pandas son homogéneas, pero pueden contener datos de diferentes tipos. Además, cada elemento en una Serie tiene una etiqueta asociada, lo que facilita la indexación y manipulación de datos.

Indexación basada en etiquetas: Las Series de Pandas utilizan etiquetas para la indexación, lo que facilita el acceso y la manipulación de datos basándose en esas etiquetas en lugar de posiciones numéricas.

Funciones de Series: Pandas proporciona funciones específicas para trabajar con Series, como operaciones de agregación, alineación de datos basada en etiquetas y manipulación de datos faltantes.

Integración con DataFrames: Las Series son la base de las columnas en un DataFrame de Pandas. Un DataFrame es una estructura de datos bidimensional que se puede ver como una colección de Series.

En resumen, mientras que los arrays de NumPy son más adecuados para operaciones numéricas eficientes y matrices multidimensionales homogéneas, las Series de Pandas son estructuras de datos más flexibles, ideales para datos etiquetados y manipulación de datos tabulares, especialmente cuando se trabaja con DataFrames en el contexto de análisis de datos.

#Series e indexación y selección de datos

In [2]:
np.array([[1,2,3,4],[6,7,8,9,]]) [0]

array([1, 2, 3, 4])

In [3]:
pd.Series ([10,9,8,7,6],[8,6,11,25,14])

8     10
6      9
11     8
25     7
14     6
dtype: int64

In [4]:
pr= pd.Series ([10,9,8,7,6],[8,6,11,25,14])

In [5]:
pr.shape

(5,)

In [6]:
pr.index

Int64Index([8, 6, 11, 25, 14], dtype='int64')

In [7]:
pr.values

array([10,  9,  8,  7,  6])

In [8]:
pr[14]

6

In [9]:
pr[[8,6,11,25,14]]

8     10
6      9
11     8
25     7
14     6
dtype: int64

In [10]:
dict_data={"CO":100,"MX":200, "AR":300}
dict_data

{'CO': 100, 'MX': 200, 'AR': 300}

In [11]:
pd.Series(dict_data)

CO    100
MX    200
AR    300
dtype: int64

In [12]:
pd.DataFrame(dict_data) #No se puede, también acepta un diccionario. Sin embargo, para que los datos se organicen en columnas y filas en un DataFrame, generalmente se espera que cada clave del diccionario sea una columna, y sus valores sean listas o arrays que representan los datos de esa columna.

ValueError: ignored

In [14]:
dict_data["CO"]

100

In [15]:
pd.Series(dict_data, index=["CO","MX","PE", "AR"]) #es desconocida y es un valor nulo

CO    100.0
MX    200.0
PE      NaN
AR    300.0
dtype: float64

In [16]:
np.nan +10

nan

In [17]:
pd.__version__

'1.5.3'

#DATAFRAME

In [50]:
dict_data= {"CH":[100,800,200], "CO" :[100,800,200], "MX":[100,800,200]}

dict_data

{'CH': [100, 800, 200], 'CO': [100, 800, 200], 'MX': [100, 800, 200]}

In [51]:
pd.DataFrame(dict_data)

CH   CO   MX
0  100  100  100
1  800  800  800
2  200  200  200

In [52]:
dict_data2={'edad' : [10,9,13,14,12,11,12],
            'cm':[115,112,158,432,345,212,100],
            'pais': ['co','mx','co','mx','mx','ch','ch'],
            'genero':['M','F','F','M','M','M','F'],
            'Q1':[5,10,8, np.NaN ,7,8,3],
            'Q2':[7,8,9,4,5,6,2]
            }


In [53]:
dict_data2

{'edad': [10, 9, 13, 14, 12, 11, 12],
 'cm': [115, 112, 158, 432, 345, 212, 100],
 'pais': ['co', 'mx', 'co', 'mx', 'mx', 'ch', 'ch'],
 'genero': ['M', 'F', 'F', 'M', 'M', 'M', 'F'],
 'Q1': [5, 10, 8, nan, 7, 8, 3],
 'Q2': [7, 8, 9, 4, 5, 6, 2]}

In [54]:
df= pd.DataFrame(dict_data2)
df

edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  112   mx      F  10.0   8
2    13  158   co      F   8.0   9
3    14  432   mx      M   NaN   4
4    12  345   mx      M   7.0   5
5    11  212   ch      M   8.0   6
6    12  100   ch      F   3.0   2

In [55]:
#agrgamos el index
df= pd.DataFrame(dict_data2,index=['ana','benito','camilo','daniel','erika','fabian','gabriela'])
df

edad   cm pais genero    Q1  Q2
ana         10  115   co      M   5.0   7
benito       9  112   mx      F  10.0   8
camilo      13  158   co      F   8.0   9
daniel      14  432   mx      M   NaN   4
erika       12  345   mx      M   7.0   5
fabian      11  212   ch      M   8.0   6
gabriela    12  100   ch      F   3.0   2

In [56]:
df.index

Index(['ana', 'benito', 'camilo', 'daniel', 'erika', 'fabian', 'gabriela'], dtype='object')

In [57]:
df.columns

Index(['edad', 'cm', 'pais', 'genero', 'Q1', 'Q2'], dtype='object')

In [58]:
df.values

array([[10, 115, 'co', 'M', 5.0, 7],
       [9, 112, 'mx', 'F', 10.0, 8],
       [13, 158, 'co', 'F', 8.0, 9],
       [14, 432, 'mx', 'M', nan, 4],
       [12, 345, 'mx', 'M', 7.0, 5],
       [11, 212, 'ch', 'M', 8.0, 6],
       [12, 100, 'ch', 'F', 3.0, 2]], dtype=object)

In [59]:
df['edad']

ana         10
benito       9
camilo      13
daniel      14
erika       12
fabian      11
gabriela    12
Name: edad, dtype: int64

In [60]:
df.loc['ana','edad']  #encontrar un valor especificil dependiendo nfila y columna


10

In [61]:
df.iloc[2,2] #encontrar un valor especificil por posición

'co'

In [62]:
df['cm'] >= 300

ana         False
benito      False
camilo      False
daniel       True
erika        True
fabian      False
gabriela    False
Name: cm, dtype: bool

In [63]:
df[df['cm'] >= 300]

edad   cm pais genero   Q1  Q2
daniel    14  432   mx      M  NaN   4
erika     12  345   mx      M  7.0   5

In [64]:
df[(df['cm'] >= 12)  & (df['pais'] == 'mx')]

edad   cm pais genero    Q1  Q2
benito     9  112   mx      F  10.0   8
daniel    14  432   mx      M   NaN   4
erika     12  345   mx      M   7.0   5

In [65]:
df.query('cm > 12 and pais=="mx"')

edad   cm pais genero    Q1  Q2
benito     9  112   mx      F  10.0   8
daniel    14  432   mx      M   NaN   4
erika     12  345   mx      M   7.0   5

#CSV

In [40]:
!pip install --upgrade pandas

In [41]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [42]:
%cd  '/content/drive/Mydrive/Colab Notebooks'
!ls

[Errno 2] No such file or directory: '/content/drive/Mydrive/Colab Notebooks'
/content
drive  sample_data


In [43]:
dict_data3={'edad' : [10,9,13,14,12,11,12],
            'cm':[115,112,158,432,345,212,100],
            'pais': ['co','mx','co','mx','mx','ch','ch'],
            'genero':['M','F','F','M','M','M','F'],
            'Q1':[5,10,8, np.NaN ,7,8,3],
            'Q2':[7,8,9,4,5,6,2]
            }

dict_data3

{'edad': [10, 9, 13, 14, 12, 11, 12],
 'cm': [115, 112, 158, 432, 345, 212, 100],
 'pais': ['co', 'mx', 'co', 'mx', 'mx', 'ch', 'ch'],
 'genero': ['M', 'F', 'F', 'M', 'M', 'M', 'F'],
 'Q1': [5, 10, 8, nan, 7, 8, 3],
 'Q2': [7, 8, 9, 4, 5, 6, 2]}

In [44]:
df=pd.DataFrame(dict_data3)
df

edad   cm pais genero    Q1  Q2
0    10  115   co      M   5.0   7
1     9  112   mx      F  10.0   8
2    13  158   co      F   8.0   9
3    14  432   mx      M   NaN   4
4    12  345   mx      M   7.0   5
5    11  212   ch      M   8.0   6
6    12  100   ch      F   3.0   2

In [45]:
dir_pandas= '/content/drive/MyDrive/Colab Notebooks/{}'.format('test.csv')
dir_pandas

'/content/drive/MyDrive/Colab Notebooks/test.csv'

In [76]:
df.to_csv(dir_pandas, sep=',', index=['ana','benito','camilo','daniel','erika','fabian','gabriela'])

df

edad   cm pais genero    Q1  Q2
ana         10  115   co      M   5.0   7
benito       9  112   mx      F  10.0   8
camilo      13  158   co      F   8.0   9
daniel      14  432   mx      M   NaN   4
erika       12  345   mx      M   7.0   5
fabian      11  212   ch      M   8.0   6
gabriela    12  100   ch      F   3.0   2