<a href="https://colab.research.google.com/github/edisonc57/exercises/blob/main/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D1%8F_%D1%81%D0%BE%D1%80%D1%82%D0%BE%D0%B2_%D0%B8%D1%80%D0%B8%D1%81%D0%B0_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from sklearn.datasets import load_iris
iris_dataset= load_iris()

In [11]:
print("Ключи iris_dataset:", iris_dataset.keys())
print("Ключи iris_dataset:".format(iris_dataset.keys()))


Ключи iris_dataset: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
Ключи iris_dataset:


In [16]:
print(iris_dataset["DESCR"][:194])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pred


In [20]:
print( iris_dataset["target_names"])

['setosa' 'versicolor' 'virginica']


In [22]:
print(iris_dataset["filename"])

iris.csv


In [48]:
print(iris_dataset["data_module"])

sklearn.datasets.data


In [35]:
print(iris_dataset["feature_names"])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [33]:
for i in range(5):
    print(iris_dataset.data[i])  #Набор данных без преобразования в Dataset pandas

[5.1 3.5 1.4 0.2]
[4.9 3.  1.4 0.2]
[4.7 3.2 1.3 0.2]
[4.6 3.1 1.5 0.2]
[5.  3.6 1.4 0.2]


In [32]:
# Преобразование набора данных в DataFrame pandas
#df = pd.DataFrame(data=iris_dataset.data, columns=iris_dataset.feature_names)

# Imprimir las primeras 5 filas
#print(df.head(5))

In [ ]:
# Загрузка набора данных
#iris_dataset = load_iris()

# Преобразование набора данных в DataFrame pandas
#df = pd.DataFrame(data=iris_dataset.data, columns=iris_dataset.feature_names)

# Печать значений определенной характеристики
#columna = df['feature_names']
#print(columna.values)


In [40]:
print("тип массива data:{}", type(iris_dataset["data"]))

тип массива data:{} <class 'numpy.ndarray'>


In [46]:
print("форма массива data:", iris_dataset["data"].shape)

форма массива data: (150, 4)


In [49]:
print(iris_dataset["data"])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.