<a href="https://colab.research.google.com/github/edisonc57/exercises/blob/main/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D1%8F_%D1%81%D0%BE%D1%80%D1%82%D0%BE%D0%B2_%D0%B8%D1%80%D0%B8%D1%81%D0%B0_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_iris
iris_dataset= load_iris()

In [2]:
print("Ключи iris_dataset:", iris_dataset.keys())
print("Ключи iris_dataset:".format(iris_dataset.keys()))


Ключи iris_dataset: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
Ключи iris_dataset:


In [3]:
print(iris_dataset["DESCR"][:194])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pred


In [4]:
print( iris_dataset["target_names"])

['setosa' 'versicolor' 'virginica']


In [5]:
print(iris_dataset["filename"])

iris.csv


In [6]:
print(iris_dataset["data_module"])

sklearn.datasets.data


In [7]:
print(iris_dataset["feature_names"])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [8]:
for i in range(5):
    print(iris_dataset.data[i])  #Набор данных без преобразования в Dataset pandas

[5.1 3.5 1.4 0.2]
[4.9 3.  1.4 0.2]
[4.7 3.2 1.3 0.2]
[4.6 3.1 1.5 0.2]
[5.  3.6 1.4 0.2]


In [ ]:
# Преобразование набора данных в DataFrame pandas
#df = pd.DataFrame(data=iris_dataset.data, columns=iris_dataset.feature_names)

# Imprimir las primeras 5 filas
#print(df.head(5))

In [ ]:
# Загрузка набора данных
#iris_dataset = load_iris()

# Преобразование набора данных в DataFrame pandas
#df = pd.DataFrame(data=iris_dataset.data, columns=iris_dataset.feature_names)

# Печать значений определенной характеристики
#columna = df['feature_names']
#print(columna.values)


In [9]:
print("тип массива data:{}", type(iris_dataset["data"]))

тип массива data:{} <class 'numpy.ndarray'>


In [10]:
print("форма массива data:", iris_dataset["data"].shape)
#Мы видим, что массив содержит измерения для 150 различных цветов по  4  признакам.

форма массива data: (150, 4)


In [11]:
print("первые 5 строк массива дата:\n", iris_dataset["data"][:5])

первые 5 строк массива дата:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [12]:

print(type(iris_dataset["target"])) #тип массива target
print(iris_dataset["target"].shape)  #форма массива  target
print(iris_dataset["target"]) #ответы

<class 'numpy.ndarray'>
(150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [20]:
#перемешиваем набор данных и разбивает его на две части. Эта функция отбирает  в  обучающий  набор  75%  строк  данных  с  соответствующими метками.  Оставшиеся  25%  данных  с  метками  объявляются  тестовым набором.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(iris_dataset["data"], iris_dataset["target"], random_state=0)

In [27]:
print("форма массива X_train: ",format(X_train.shape))
print("форма массива y_train", format(y_train.shape))
print(X_train)
print(y_train)

форма массива X_train:  (112, 4)
форма массива y_train (112,)
[[5.9 3.  4.2 1.5]
 [5.8 2.6 4.  1.2]
 [6.8 3.  5.5 2.1]
 [4.7 3.2 1.3 0.2]
 [6.9 3.1 5.1 2.3]
 [5.  3.5 1.6 0.6]
 [5.4 3.7 1.5 0.2]
 [5.  2.  3.5 1. ]
 [6.5 3.  5.5 1.8]
 [6.7 3.3 5.7 2.5]
 [6.  2.2 5.  1.5]
 [6.7 2.5 5.8 1.8]
 [5.6 2.5 3.9 1.1]
 [7.7 3.  6.1 2.3]
 [6.3 3.3 4.7 1.6]
 [5.5 2.4 3.8 1.1]
 [6.3 2.7 4.9 1.8]
 [6.3 2.8 5.1 1.5]
 [4.9 2.5 4.5 1.7]
 [6.3 2.5 5.  1.9]
 [7.  3.2 4.7 1.4]
 [6.5 3.  5.2 2. ]
 [6.  3.4 4.5 1.6]
 [4.8 3.1 1.6 0.2]
 [5.8 2.7 5.1 1.9]
 [5.6 2.7 4.2 1.3]
 [5.6 2.9 3.6 1.3]
 [5.5 2.5 4.  1.3]
 [6.1 3.  4.6 1.4]
 [7.2 3.2 6.  1.8]
 [5.3 3.7 1.5 0.2]
 [4.3 3.  1.1 0.1]
 [6.4 2.7 5.3 1.9]
 [5.7 3.  4.2 1.2]
 [5.4 3.4 1.7 0.2]
 [5.7 4.4 1.5 0.4]
 [6.9 3.1 4.9 1.5]
 [4.6 3.1 1.5 0.2]
 [5.9 3.  5.1 1.8]
 [5.1 2.5 3.  1.1]
 [4.6 3.4 1.4 0.3]
 [6.2 2.2 4.5 1.5]
 [7.2 3.6 6.1 2.5]
 [5.7 2.9 4.2 1.3]
 [4.8 3.  1.4 0.1]
 [7.1 3.  5.9 2.1]
 [6.9 3.2 5.7 2.3]
 [6.5 3.  5.8 2.2]
 [6.4 2.8 5.6 2.1]
 [5.1 3

In [28]:
print("форма массива X_test: ",format(X_test.shape))
print("форма массива y_test", format(y_test.shape))
print(X_test)
print(y_test)

форма массива X_test:  (38, 4)
форма массива y_test (38,)
[[5.8 2.8 5.1 2.4]
 [6.  2.2 4.  1. ]
 [5.5 4.2 1.4 0.2]
 [7.3 2.9 6.3 1.8]
 [5.  3.4 1.5 0.2]
 [6.3 3.3 6.  2.5]
 [5.  3.5 1.3 0.3]
 [6.7 3.1 4.7 1.5]
 [6.8 2.8 4.8 1.4]
 [6.1 2.8 4.  1.3]
 [6.1 2.6 5.6 1.4]
 [6.4 3.2 4.5 1.5]
 [6.1 2.8 4.7 1.2]
 [6.5 2.8 4.6 1.5]
 [6.1 2.9 4.7 1.4]
 [4.9 3.6 1.4 0.1]
 [6.  2.9 4.5 1.5]
 [5.5 2.6 4.4 1.2]
 [4.8 3.  1.4 0.3]
 [5.4 3.9 1.3 0.4]
 [5.6 2.8 4.9 2. ]
 [5.6 3.  4.5 1.5]
 [4.8 3.4 1.9 0.2]
 [4.4 2.9 1.4 0.2]
 [6.2 2.8 4.8 1.8]
 [4.6 3.6 1.  0.2]
 [5.1 3.8 1.9 0.4]
 [6.2 2.9 4.3 1.3]
 [5.  2.3 3.3 1. ]
 [5.  3.4 1.6 0.4]
 [6.4 3.1 5.5 1.8]
 [5.4 3.  4.5 1.5]
 [5.2 3.5 1.5 0.2]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.2]
 [5.2 2.7 3.9 1.4]
 [5.7 3.8 1.7 0.3]
 [6.  2.7 5.1 1.6]]
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1]
